/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileChooserJFrame.java
 *
 * Created on Apr 26, 2011, 3:34:03 PM
 *
 * 02.16.2013 added a constructor to accept location from IESTelemetryview
 */


package iestelemetry;
import javax.swing.*;
import java.io.*;
/**
 *
 * @author Pedro Pena
 */
public class FileChooserJFrame extends javax.swing.JFrame {

    JTextField fileLocation = null;
    File thePath =null;
    String pWD = null;

    /** Creates new form FileChooserJFrame */
    public FileChooserJFrame() {
        
        initComponents();
        

    }
        public FileChooserJFrame(String f) {
            System.out.println(f);
                    
        thePath = new File(f);
        initComponents();
        

    }
    
    
    public void setJTextField(JTextField ff){

        fileLocation = ff;
        thePath = new File("");
        pWD = thePath.getAbsolutePath();

    };

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SaveFileLocationjFileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        SaveFileLocationjFileChooser.setCurrentDirectory(thePath);
        SaveFileLocationjFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        SaveFileLocationjFileChooser.setName("SaveFileLocationjFileChooser"); // NOI18N
        SaveFileLocationjFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFileLocationjFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaveFileLocationjFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaveFileLocationjFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveFileLocationjFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFileLocationjFileChooserActionPerformed
        // TODO add your handling code here:
        //switch (evt.getActionCommand()){}// end switch
        String event = evt.getActionCommand();
        if(event.equals("ApproveSelection")){
            //String path = SaveFileLocationjFileChooser.getCurrentDirectory().getAbsolutePath();
            String path = SaveFileLocationjFileChooser.getSelectedFile().getAbsolutePath();
            System.out.println("accepted\n"+path);
            this.fileLocation.setText(path);

            this.dispose();
        }// end approve if

        if(event.equals("CancelSelection")){
            this.dispose();
        }// end close if
        //System.out.println(event);
    }//GEN-LAST:event_SaveFileLocationjFileChooserActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                   
            new FileChooserJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser SaveFileLocationjFileChooser;
    // End of variables declaration//GEN-END:variables



}// end class
